// <auto-generated />
using System;
using GestaoDocumental.Infrastructure.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GestaoDocumental.Infrastructure.Data.Migrations
{
    [DbContext(typeof(GestaoDocumentalDbContext))]
    [Migration("20260525142747_FixUsuarioSistemaColaboradorNullable")]
    partial class FixUsuarioSistemaColaboradorNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GestaoDocumental.Domain.Entities.Legacy.ClassificacaoDocumento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id")
                        .HasName("PK__Classifi__3214EC07029D907A");

                    b.ToTable("ClassificacaoDocumento", (string)null);
                });

            modelBuilder.Entity("GestaoDocumental.Domain.Entities.Legacy.Colaborador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Cargo")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataNascimento")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Endereco")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("EstadoId")
                        .HasColumnType("int");

                    b.Property<int?>("GeneroId")
                        .HasColumnType("int");

                    b.Property<int?>("NacionalidadeId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("NumDocumento")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NumMecanografo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("PerfilId")
                        .HasColumnType("int");

                    b.Property<int>("PostoTrabalhoId")
                        .HasColumnType("int");

                    b.Property<int>("TipoDocumentoColaboradorId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Colabora__3214EC07DDF45E41");

                    b.HasIndex("EstadoId");

                    b.HasIndex("GeneroId");

                    b.HasIndex("NacionalidadeId");

                    b.HasIndex("PerfilId");

                    b.HasIndex("PostoTrabalhoId");

                    b.HasIndex("TipoDocumentoColaboradorId");

                    b.HasIndex(new[] { "NumDocumento" }, "UQ__Colabora__11150A80B24E655E")
                        .IsUnique();

                    b.ToTable("Colaborador", (string)null);
                });

            modelBuilder.Entity("GestaoDocumental.Domain.Entities.Legacy.Departamento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("DirecaoId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Sigla")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__Departam__3214EC077DA0D7C6");

                    b.HasIndex("DirecaoId");

                    b.ToTable("Departamento", (string)null);
                });

            modelBuilder.Entity("GestaoDocumental.Domain.Entities.Legacy.Direcao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Sigla")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__Direcao__3214EC0720D379A2");

                    b.ToTable("Direcao", (string)null);
                });

            modelBuilder.Entity("GestaoDocumental.Domain.Entities.Legacy.Documento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<int>("ClassificacaoId")
                        .HasColumnType("int");

                    b.Property<string>("CodigoArquivo")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("ColaboradorCriadorId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DataDocumento")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DataRecepcao")
                        .HasColumnType("datetime");

                    b.Property<string>("Descricao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DirecaoOrigemId")
                        .HasColumnType("int");

                    b.Property<int>("EstadoDocumentoId")
                        .HasColumnType("int");

                    b.Property<int?>("FornecedorId")
                        .HasColumnType("int");

                    b.Property<string>("LocalizacaoFisica")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("NumeroDocumento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Observacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PalavrasChave")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateTime?>("PrazoResposta")
                        .HasColumnType("datetime");

                    b.Property<string>("ReferenciaExterna")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("TipoDocumentoId")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("UtilizadorAtualizacaoId")
                        .HasColumnType("int");

                    b.Property<int?>("VersaoAtual")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("Id")
                        .HasName("PK__Document__3214EC07B81173F0");

                    b.HasIndex("ClassificacaoId");

                    b.HasIndex("ColaboradorCriadorId");

                    b.HasIndex("DirecaoOrigemId");

                    b.HasIndex("EstadoDocumentoId");

                    b.HasIndex("FornecedorId");

                    b.HasIndex("TipoDocumentoId");

                    b.HasIndex("UtilizadorAtualizacaoId");

                    b.HasIndex(new[] { "NumeroDocumento" }, "UQ__Document__A4202588CF4E8E6F")
                        .IsUnique();

                    b.ToTable("Documento", (string)null);
                });

            modelBuilder.Entity("GestaoDocumental.Domain.Entities.Legacy.DocumentoAnexo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("Caminho")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataUpload")
                        .HasColumnType("datetime");

                    b.Property<int>("DocumentoId")
                        .HasColumnType("int");

                    b.Property<string>("Extensao")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("GuidFicheiro")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HashSha256")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("HashSHA256");

                    b.Property<string>("NomeFisico")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("NomeOriginal")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<long?>("Tamanho")
                        .HasColumnType("bigint");

                    b.HasKey("Id")
                        .HasName("PK__Document__3214EC07B7B11007");

                    b.HasIndex("DocumentoId");

                    b.ToTable("DocumentoAnexo", (string)null);
                });

            modelBuilder.Entity("GestaoDocumental.Domain.Entities.Legacy.DocumentoHistorico", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Acao")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime>("DataAcao")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("DocumentoId")
                        .HasColumnType("int");

                    b.Property<string>("Observacao")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UtilizadorId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Document__3214EC072769FB03");

                    b.HasIndex("DocumentoId");

                    b.HasIndex("UtilizadorId");

                    b.ToTable("DocumentoHistorico", (string)null);
                });

            modelBuilder.Entity("GestaoDocumental.Domain.Entities.Legacy.EstadoColaborador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__EstadoCo__3214EC07BEA7D5A8");

                    b.ToTable("EstadoColaborador", (string)null);
                });

            modelBuilder.Entity("GestaoDocumental.Domain.Entities.Legacy.EstadoDocumento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__EstadoDo__3214EC0722AE2348");

                    b.ToTable("EstadoDocumento", (string)null);
                });

            modelBuilder.Entity("GestaoDocumental.Domain.Entities.Legacy.EstadoLogin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__EstadoLo__3214EC0740BD35AB");

                    b.ToTable("EstadoLogin", (string)null);
                });

            modelBuilder.Entity("GestaoDocumental.Domain.Entities.Legacy.Fornecedor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<string>("ContactoAlternativo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ContactoPrincipal")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email1")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Email2")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<string>("Endereco")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("Nif")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Notas")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PontoFocal")
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id")
                        .HasName("PK__Forneced__3214EC07092DD836");

                    b.ToTable("Fornecedor", (string)null);
                });

            modelBuilder.Entity("GestaoDocumental.Domain.Entities.Legacy.Genero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Genero__3214EC074B76DBEE");

                    b.ToTable("Genero", (string)null);
                });

            modelBuilder.Entity("GestaoDocumental.Domain.Entities.Legacy.Municipio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("ProvinciaId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Municipi__3214EC07607074F2");

                    b.HasIndex("ProvinciaId");

                    b.ToTable("Municipio", (string)null);
                });

            modelBuilder.Entity("GestaoDocumental.Domain.Entities.Legacy.Pais", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id")
                        .HasName("PK__Pais__3214EC077903404E");

                    b.ToTable("Pais");
                });

            modelBuilder.Entity("GestaoDocumental.Domain.Entities.Legacy.Perfil", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("Id")
                        .HasName("PK__Perfil__3214EC0748F25AA8");

                    b.ToTable("Perfil", (string)null);
                });

            modelBuilder.Entity("GestaoDocumental.Domain.Entities.Legacy.PostoTrabalho", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartamentoId")
                        .HasColumnType("int");

                    b.Property<int>("MunicipioId")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Sigla")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Id")
                        .HasName("PK__PostoTra__3214EC078C795F02");

                    b.HasIndex("DepartamentoId");

                    b.HasIndex("MunicipioId");

                    b.ToTable("PostoTrabalho", (string)null);
                });

            modelBuilder.Entity("GestaoDocumental.Domain.Entities.Legacy.Provincia", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<int>("PaisId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK__Provinci__3214EC0776531CA7");

                    b.HasIndex("PaisId");

                    b.ToTable("Provincia");
                });

            modelBuilder.Entity("GestaoDocumental.Domain.Entities.Legacy.TipoDocumento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__TipoDocu__3214EC07670A5546");

                    b.ToTable("TipoDocumento", (string)null);
                });

            modelBuilder.Entity("GestaoDocumental.Domain.Entities.Legacy.TipoDocumentoColaborador", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__TipoDocu__3214EC075DFCDEC9");

                    b.ToTable("TipoDocumentoColaborador", (string)null);
                });

            modelBuilder.Entity("GestaoDocumental.Domain.Entities.Legacy.TramitacaoDocumento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .HasColumnType("bit");

                    b.Property<int?>("ColaboradorDestinoId")
                        .HasColumnType("int");

                    b.Property<int?>("ColaboradorOrigemId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataEnvio")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("DataRececao")
                        .HasColumnType("datetime");

                    b.Property<int>("DirecaoDestinoId")
                        .HasColumnType("int");

                    b.Property<int>("DirecaoOrigemId")
                        .HasColumnType("int");

                    b.Property<int>("DocumentoId")
                        .HasColumnType("int");

                    b.Property<string>("Estado")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Observacao")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id")
                        .HasName("PK__Tramitac__3214EC0704B9FC07");

                    b.HasIndex("ColaboradorDestinoId");

                    b.HasIndex("ColaboradorOrigemId");

                    b.HasIndex("DirecaoDestinoId");

                    b.HasIndex("DirecaoOrigemId");

                    b.HasIndex("DocumentoId");

                    b.ToTable("TramitacaoDocumento", (string)null);
                });

            modelBuilder.Entity("GestaoDocumental.Domain.Entities.Legacy.UsuarioSistema", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<bool>("Bloqueado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<int?>("ColaboradorId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DataAtualizacao")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("EstadoLoginId")
                        .HasColumnType("int");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("PerfilId")
                        .HasColumnType("int");

                    b.Property<int>("TentativasLogin")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(0)
                        .HasColumnName("TentativasFalhadas");

                    b.Property<DateTime?>("UltimoLogin")
                        .HasColumnType("datetime");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id")
                        .HasName("PK__UsuarioS__3214EC07AC565DAA");

                    b.HasIndex("EstadoLoginId");

                    b.HasIndex("PerfilId");

                    b.HasIndex(new[] { "Email" }, "UQ_UsuarioSistema_Email")
                        .IsUnique();

                    b.HasIndex(new[] { "ColaboradorId" }, "UQ__UsuarioS__28AA72205B486489")
                        .IsUnique()
                        .HasFilter("[ColaboradorId] IS NOT NULL");

                    b.HasIndex(new[] { "Username" }, "UQ__UsuarioS__536C85E4126F4AB7")
                        .IsUnique();

                    b.ToTable("UsuarioSistema", (string)null);
                });

            modelBuilder.Entity("GestaoDocumental.Domain.Entities.Legacy.Colaborador", b =>
                {
                    b.HasOne("GestaoDocumental.Domain.Entities.Legacy.EstadoColaborador", "Estado")
                        .WithMany("Colaboradors")
                        .HasForeignKey("EstadoId")
                        .IsRequired()
                        .HasConstraintName("FK__Colaborad__Estad__5AEE82B9");

                    b.HasOne("GestaoDocumental.Domain.Entities.Legacy.Genero", "Genero")
                        .WithMany("Colaboradors")
                        .HasForeignKey("GeneroId")
                        .HasConstraintName("FK__Colaborad__Gener__59FA5E80");

                    b.HasOne("GestaoDocumental.Domain.Entities.Legacy.Pais", "Nacionalidade")
                        .WithMany("Colaboradors")
                        .HasForeignKey("NacionalidadeId")
                        .HasConstraintName("FK__Colaborad__Nacio__5812160E");

                    b.HasOne("GestaoDocumental.Domain.Entities.Legacy.Perfil", "Perfil")
                        .WithMany("Colaboradors")
                        .HasForeignKey("PerfilId")
                        .IsRequired()
                        .HasConstraintName("FK__Colaborad__Perfi__5DCAEF64");

                    b.HasOne("GestaoDocumental.Domain.Entities.Legacy.PostoTrabalho", "PostoTrabalho")
                        .WithMany("Colaboradors")
                        .HasForeignKey("PostoTrabalhoId")
                        .IsRequired()
                        .HasConstraintName("FK__Colaborad__Posto__59063A47");

                    b.HasOne("GestaoDocumental.Domain.Entities.Legacy.TipoDocumentoColaborador", "TipoDocumentoColaborador")
                        .WithMany("Colaboradors")
                        .HasForeignKey("TipoDocumentoColaboradorId")
                        .IsRequired()
                        .HasConstraintName("FK__Colaborad__TipoD__571DF1D5");

                    b.Navigation("Estado");

                    b.Navigation("Genero");

                    b.Navigation("Nacionalidade");

                    b.Navigation("Perfil");

                    b.Navigation("PostoTrabalho");

                    b.Navigation("TipoDocumentoColaborador");
                });

            modelBuilder.Entity("GestaoDocumental.Domain.Entities.Legacy.Departamento", b =>
                {
                    b.HasOne("GestaoDocumental.Domain.Entities.Legacy.Direcao", "Direcao")
                        .WithMany("Departamentos")
                        .HasForeignKey("DirecaoId")
                        .IsRequired()
                        .HasConstraintName("FK__Departame__Direc__5441852A");

                    b.Navigation("Direcao");
                });

            modelBuilder.Entity("GestaoDocumental.Domain.Entities.Legacy.Documento", b =>
                {
                    b.HasOne("GestaoDocumental.Domain.Entities.Legacy.ClassificacaoDocumento", "Classificacao")
                        .WithMany("Documentos")
                        .HasForeignKey("ClassificacaoId")
                        .IsRequired()
                        .HasConstraintName("FK__Documento__Class__5FB337D6");

                    b.HasOne("GestaoDocumental.Domain.Entities.Legacy.Colaborador", "ColaboradorCriador")
                        .WithMany("DocumentoColaboradorCriadors")
                        .HasForeignKey("ColaboradorCriadorId")
                        .IsRequired()
                        .HasConstraintName("FK__Documento__Colab__628FA481");

                    b.HasOne("GestaoDocumental.Domain.Entities.Legacy.Direcao", "DirecaoOrigem")
                        .WithMany("Documentos")
                        .HasForeignKey("DirecaoOrigemId")
                        .IsRequired()
                        .HasConstraintName("FK__Documento__Direc__619B8048");

                    b.HasOne("GestaoDocumental.Domain.Entities.Legacy.EstadoDocumento", "EstadoDocumento")
                        .WithMany("Documentos")
                        .HasForeignKey("EstadoDocumentoId")
                        .IsRequired()
                        .HasConstraintName("FK__Documento__Estad__60A75C0F");

                    b.HasOne("GestaoDocumental.Domain.Entities.Legacy.Fornecedor", "Fornecedor")
                        .WithMany("Documentos")
                        .HasForeignKey("FornecedorId")
                        .HasConstraintName("FK__Documento__Forne__6383C8BA");

                    b.HasOne("GestaoDocumental.Domain.Entities.Legacy.TipoDocumento", "TipoDocumento")
                        .WithMany("Documentos")
                        .HasForeignKey("TipoDocumentoId")
                        .IsRequired()
                        .HasConstraintName("FK__Documento__TipoD__5EBF139D");

                    b.HasOne("GestaoDocumental.Domain.Entities.Legacy.Colaborador", "UtilizadorAtualizacao")
                        .WithMany("DocumentoUtilizadorAtualizacaos")
                        .HasForeignKey("UtilizadorAtualizacaoId")
                        .HasConstraintName("FK__Documento__Utili__6477ECF3");

                    b.Navigation("Classificacao");

                    b.Navigation("ColaboradorCriador");

                    b.Navigation("DirecaoOrigem");

                    b.Navigation("EstadoDocumento");

                    b.Navigation("Fornecedor");

                    b.Navigation("TipoDocumento");

                    b.Navigation("UtilizadorAtualizacao");
                });

            modelBuilder.Entity("GestaoDocumental.Domain.Entities.Legacy.DocumentoAnexo", b =>
                {
                    b.HasOne("GestaoDocumental.Domain.Entities.Legacy.Documento", "Documento")
                        .WithMany("DocumentoAnexos")
                        .HasForeignKey("DocumentoId")
                        .IsRequired()
                        .HasConstraintName("FK__Documento__Docum__656C112C");

                    b.Navigation("Documento");
                });

            modelBuilder.Entity("GestaoDocumental.Domain.Entities.Legacy.DocumentoHistorico", b =>
                {
                    b.HasOne("GestaoDocumental.Domain.Entities.Legacy.Documento", "Documento")
                        .WithMany("DocumentoHistoricos")
                        .HasForeignKey("DocumentoId")
                        .IsRequired()
                        .HasConstraintName("FK__Documento__Docum__66603565");

                    b.HasOne("GestaoDocumental.Domain.Entities.Legacy.Colaborador", "Utilizador")
                        .WithMany("DocumentoHistoricos")
                        .HasForeignKey("UtilizadorId")
                        .IsRequired()
                        .HasConstraintName("FK__Documento__Utili__6754599E");

                    b.Navigation("Documento");

                    b.Navigation("Utilizador");
                });

            modelBuilder.Entity("GestaoDocumental.Domain.Entities.Legacy.Municipio", b =>
                {
                    b.HasOne("GestaoDocumental.Domain.Entities.Legacy.Provincia", "Provincia")
                        .WithMany("Municipios")
                        .HasForeignKey("ProvinciaId")
                        .IsRequired()
                        .HasConstraintName("FK__Municipio__Provi__534D60F1");

                    b.Navigation("Provincia");
                });

            modelBuilder.Entity("GestaoDocumental.Domain.Entities.Legacy.PostoTrabalho", b =>
                {
                    b.HasOne("GestaoDocumental.Domain.Entities.Legacy.Departamento", "Departamento")
                        .WithMany("PostoTrabalhos")
                        .HasForeignKey("DepartamentoId")
                        .IsRequired()
                        .HasConstraintName("FK__PostoTrab__Depar__5535A963");

                    b.HasOne("GestaoDocumental.Domain.Entities.Legacy.Municipio", "Municipio")
                        .WithMany("PostoTrabalhos")
                        .HasForeignKey("MunicipioId")
                        .IsRequired()
                        .HasConstraintName("FK__PostoTrab__Munic__5629CD9C");

                    b.Navigation("Departamento");

                    b.Navigation("Municipio");
                });

            modelBuilder.Entity("GestaoDocumental.Domain.Entities.Legacy.Provincia", b =>
                {
                    b.HasOne("GestaoDocumental.Domain.Entities.Legacy.Pais", "Pais")
                        .WithMany("Provincia")
                        .HasForeignKey("PaisId")
                        .IsRequired()
                        .HasConstraintName("FK__Provincia__PaisI__52593CB8");

                    b.Navigation("Pais");
                });

            modelBuilder.Entity("GestaoDocumental.Domain.Entities.Legacy.TramitacaoDocumento", b =>
                {
                    b.HasOne("GestaoDocumental.Domain.Entities.Legacy.Colaborador", "ColaboradorDestino")
                        .WithMany("TramitacaoDocumentoColaboradorDestinos")
                        .HasForeignKey("ColaboradorDestinoId")
                        .HasConstraintName("FK__Tramitaca__Colab__6C190EBB");

                    b.HasOne("GestaoDocumental.Domain.Entities.Legacy.Colaborador", "ColaboradorOrigem")
                        .WithMany("TramitacaoDocumentoColaboradorOrigems")
                        .HasForeignKey("ColaboradorOrigemId")
                        .HasConstraintName("FK__Tramitaca__Colab__6B24EA82");

                    b.HasOne("GestaoDocumental.Domain.Entities.Legacy.Direcao", "DirecaoDestino")
                        .WithMany("TramitacaoDocumentoDirecaoDestinos")
                        .HasForeignKey("DirecaoDestinoId")
                        .IsRequired()
                        .HasConstraintName("FK__Tramitaca__Direc__6A30C649");

                    b.HasOne("GestaoDocumental.Domain.Entities.Legacy.Direcao", "DirecaoOrigem")
                        .WithMany("TramitacaoDocumentoDirecaoOrigems")
                        .HasForeignKey("DirecaoOrigemId")
                        .IsRequired()
                        .HasConstraintName("FK__Tramitaca__Direc__693CA210");

                    b.HasOne("GestaoDocumental.Domain.Entities.Legacy.Documento", "Documento")
                        .WithMany("TramitacaoDocumentos")
                        .HasForeignKey("DocumentoId")
                        .IsRequired()
                        .HasConstraintName("FK__Tramitaca__Docum__68487DD7");

                    b.Navigation("ColaboradorDestino");

                    b.Navigation("ColaboradorOrigem");

                    b.Navigation("DirecaoDestino");

                    b.Navigation("DirecaoOrigem");

                    b.Navigation("Documento");
                });

            modelBuilder.Entity("GestaoDocumental.Domain.Entities.Legacy.UsuarioSistema", b =>
                {
                    b.HasOne("GestaoDocumental.Domain.Entities.Legacy.Colaborador", "Colaborador")
                        .WithOne("UsuarioSistema")
                        .HasForeignKey("GestaoDocumental.Domain.Entities.Legacy.UsuarioSistema", "ColaboradorId")
                        .HasConstraintName("FK__UsuarioSi__Colab__5BE2A6F2");

                    b.HasOne("GestaoDocumental.Domain.Entities.Legacy.EstadoLogin", "EstadoLogin")
                        .WithMany("UsuarioSistemas")
                        .HasForeignKey("EstadoLoginId")
                        .IsRequired()
                        .HasConstraintName("FK__UsuarioSi__Estad__5CD6CB2B");

                    b.HasOne("GestaoDocumental.Domain.Entities.Legacy.Perfil", "Perfil")
                        .WithMany("UsuarioSistemas")
                        .HasForeignKey("PerfilId")
                        .IsRequired()
                        .HasConstraintName("FK_UsuarioSistema_Perfil");

                    b.Navigation("Colaborador");

                    b.Navigation("EstadoLogin");

                    b.Navigation("Perfil");
                });

            modelBuilder.Entity("GestaoDocumental.Domain.Entities.Legacy.ClassificacaoDocumento", b =>
                {
                    b.Navigation("Documentos");
                });

            modelBuilder.Entity("GestaoDocumental.Domain.Entities.Legacy.Colaborador", b =>
                {
                    b.Navigation("DocumentoColaboradorCriadors");

                    b.Navigation("DocumentoHistoricos");

                    b.Navigation("DocumentoUtilizadorAtualizacaos");

                    b.Navigation("TramitacaoDocumentoColaboradorDestinos");

                    b.Navigation("TramitacaoDocumentoColaboradorOrigems");

                    b.Navigation("UsuarioSistema");
                });

            modelBuilder.Entity("GestaoDocumental.Domain.Entities.Legacy.Departamento", b =>
                {
                    b.Navigation("PostoTrabalhos");
                });

            modelBuilder.Entity("GestaoDocumental.Domain.Entities.Legacy.Direcao", b =>
                {
                    b.Navigation("Departamentos");

                    b.Navigation("Documentos");

                    b.Navigation("TramitacaoDocumentoDirecaoDestinos");

                    b.Navigation("TramitacaoDocumentoDirecaoOrigems");
                });

            modelBuilder.Entity("GestaoDocumental.Domain.Entities.Legacy.Documento", b =>
                {
                    b.Navigation("DocumentoAnexos");

                    b.Navigation("DocumentoHistoricos");

                    b.Navigation("TramitacaoDocumentos");
                });

            modelBuilder.Entity("GestaoDocumental.Domain.Entities.Legacy.EstadoColaborador", b =>
                {
                    b.Navigation("Colaboradors");
                });

            modelBuilder.Entity("GestaoDocumental.Domain.Entities.Legacy.EstadoDocumento", b =>
                {
                    b.Navigation("Documentos");
                });

            modelBuilder.Entity("GestaoDocumental.Domain.Entities.Legacy.EstadoLogin", b =>
                {
                    b.Navigation("UsuarioSistemas");
                });

            modelBuilder.Entity("GestaoDocumental.Domain.Entities.Legacy.Fornecedor", b =>
                {
                    b.Navigation("Documentos");
                });

            modelBuilder.Entity("GestaoDocumental.Domain.Entities.Legacy.Genero", b =>
                {
                    b.Navigation("Colaboradors");
                });

            modelBuilder.Entity("GestaoDocumental.Domain.Entities.Legacy.Municipio", b =>
                {
                    b.Navigation("PostoTrabalhos");
                });

            modelBuilder.Entity("GestaoDocumental.Domain.Entities.Legacy.Pais", b =>
                {
                    b.Navigation("Colaboradors");

                    b.Navigation("Provincia");
                });

            modelBuilder.Entity("GestaoDocumental.Domain.Entities.Legacy.Perfil", b =>
                {
                    b.Navigation("Colaboradors");

                    b.Navigation("UsuarioSistemas");
                });

            modelBuilder.Entity("GestaoDocumental.Domain.Entities.Legacy.PostoTrabalho", b =>
                {
                    b.Navigation("Colaboradors");
                });

            modelBuilder.Entity("GestaoDocumental.Domain.Entities.Legacy.Provincia", b =>
                {
                    b.Navigation("Municipios");
                });

            modelBuilder.Entity("GestaoDocumental.Domain.Entities.Legacy.TipoDocumento", b =>
                {
                    b.Navigation("Documentos");
                });

            modelBuilder.Entity("GestaoDocumental.Domain.Entities.Legacy.TipoDocumentoColaborador", b =>
                {
                    b.Navigation("Colaboradors");
                });
#pragma warning restore 612, 618
        }
    }
}
